# Generated by Django 3.0.8 on 2020-07-29 22:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chitchat', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfile',
            new_name='user_Profile',
        ),
    ]
