# Generated by Django 3.0.8 on 2020-07-30 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat', '0004_auto_20200730_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='name',
            new_name='user',
        ),
    ]
